RegisterCommand("911", function(source, args, rawCommand)
    TriggerEvent('chatMessage', "^3To use ^1/911 ^3Use either ^1/911pd^0, ^1/911ems^0, ^1/911fd or /911all ^3For all departments, critical emergencies only!")
end, false)

RegisterCommand("911pd", function(source, args, rawCommand)
    local ped = PlayerPedId()
    local x,y,z = table.unpack(GetEntityCoords(ped, false))
    local street = GetStreetNameAtCoord(x, y, z)
    street = GetStreetNameFromHashKey(street)
    local name = GetPlayerName(_source)
    local message = table.concat(args, " ")
    TriggerEvent('chatMessage', "^1911 [Police] - Caller ID | " .. name .. "^0:^3 Location: ^0" .. street .. " ^3Incident", { 255, 187, 51 }, message)
end, false)

RegisterCommand("911ems", function(source, args, rawCommand)
    local ped = PlayerPedId()
    local x,y,z = table.unpack(GetEntityCoords(ped, false))
    local street = GetStreetNameAtCoord(x, y, z)
    street = GetStreetNameFromHashKey(street)
    local name = GetPlayerName(_source)
    local message = table.concat(args, " ")
    TriggerEvent('chatMessage', "^4911 [EMS] - Caller ID | " .. name .. "^0:^3 Location: ^0" .. street .. " ^3Incident", { 255, 187, 51 }, message)
end, false)

RegisterCommand("911fd", function(source, args, rawCommand)
    local ped = PlayerPedId()
    local x,y,z = table.unpack(GetEntityCoords(ped, false))
    local street = GetStreetNameAtCoord(x, y, z)
    street = GetStreetNameFromHashKey(street)
    local name = GetPlayerName(_source)
    local message = table.concat(args, " ")
    TriggerEvent('chatMessage', "^1911 [Fire] - Caller ID | " .. name .. "^0:^3 Location: ^0" .. street .. " ^3Incident", { 255, 187, 51 }, message)
end, false)

RegisterCommand("911all", function(source, args, rawCommand)
    local ped = PlayerPedId()
    local x,y,z = table.unpack(GetEntityCoords(ped, false))
    local street = GetStreetNameAtCoord(x, y, z)
    street = GetStreetNameFromHashKey(street)
    local name = GetPlayerName(_source)
    local message = table.concat(args, " ")
    TriggerEvent('chatMessage', "^1911 [ALL] - Caller ID | " .. name .. "^0:^3 Location: ^0" .. street .. " ^3Incident", { 255, 187, 51 }, message)
end, false)
